### ISSUE TITLE
Idea : Collab with other open source contributor ?

### ISSUE THREAD

**Issue by WongYC-66** [razmans/mykad#3]
As per : https://github.com/wmthor/mykad/issues/18

From search, found other has built something similar, perhaps some collab opportunity to avoid reinventing wheel ?

**Comment by razmans** [comment]
The idea that I have here is to try to build for JSR generally and for deno specifically. I thought it would be a great idea to have something like this on a new platform like JSR.io, which is going to be an npm alternative. 

I don't see a lot of dependencies to collab.
